name: Publish Docker image

on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.1
          
      - name: Log in to Github
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: |
           ghcr.io/${{ github.repository }}
          
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
        with:
          platforms: linux/amd64, linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Build and push Docker image AMD64
        uses: docker/build-push-action@v5.0.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            ghcr.io/almir1904/anilistbackup:latest
          labels: ${{ steps.meta.outputs.labels }}
